# Generated by Django 2.1.4 on 2018-12-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleItem',
            new_name='ScheduledItem',
        ),
    ]
